Repository skyplane-project/skyplane, pull requests merged in 2022-10, with the labels that each got.

#601 Update documentation with link to benchmarks and architecture
  README.md
  docs/_static/skyplane-data-plane.png
Labels: documentation

#613 Fix Azure core import issue
  skyplane/cli/cli_impl/init.py
  skyplane/compute/azure/azure_server.py
Labels: bug

#617 Clean up leaked resources upon VM provisioning errors for AWS, GCP and Azure
  skyplane/cli/cli_impl/cp_replicate.py
  skyplane/compute/aws/aws_cloud_provider.py
  skyplane/compute/azure/azure_cloud_provider.py
  skyplane/compute/gcp/gcp_cloud_provider.py
  skyplane/replicate/replicator_client.py
Labels: bug

#616 Prefix AWS keys with UUID, tag VMs with UUID
  skyplane/cli/cli.py
  skyplane/cli/cli_impl/cp_replicate.py
  skyplane/cli/cli_internal.py
  skyplane/compute/aws/aws_key_manager.py
  skyplane/compute/aws/aws_server.py
  skyplane/config.py
  skyplane/replicate/replicator_client.py
Labels: bug

#632 Use questionary to allow selection of multiple Azure subscriptions
  poetry.lock
  pyproject.toml
  skyplane/cli/cli_impl/init.py
Labels: CLI

#630 azure: add 'tags' argument to provision_instance
  poetry.lock
  pyproject.toml
  skyplane/compute/azure/azure_cloud_provider.py
Labels: safe to test

#635 [API] Extract provisioner logic into separate class
  skyplane/api/auth_config.py
  skyplane/api/dataplane.py
  skyplane/api/impl/provisioner.py
  skyplane/compute/aws/aws_cloud_provider.py
  skyplane/compute/azure/azure_cloud_provider.py
  skyplane/compute/cloud_providers.py
  skyplane/compute/gcp/gcp_cloud_provider.py
  skyplane/obj_store/azure_blob_interface.py
  skyplane/obj_store/gcs_interface.py
  skyplane/obj_store/object_store_interface.py
  skyplane/obj_store/s3_interface.py
Labels: api

#650 Fix broken Azure path logic
  skyplane/cli/cli_azure.py
  skyplane/cli/common.py
  tests/unit_nocloud/test_common.py
Labels: bug
