Repository skyplane-project/skyplane, pull requests merged in 2022-12, with the labels that each got.

#677 [api] Migrate CLI over the API
  docs/index.rst
  docs/skyplane_cli_internal.rst
  docs/skyplane_internal.rst
  skyplane/__init__.py
  skyplane/api/client.py
  skyplane/api/dataplane.py
  skyplane/api/provisioner.py
  skyplane/api/tracker.py
  skyplane/api/transfer_job.py
  skyplane/api/usage.py
  skyplane/broadcast/gateway/gateway_daemon_api.py
  skyplane/cli/cli.py
  skyplane/cli/cli_config.py
  skyplane/cli/cli_impl/cp_replicate.py
  skyplane/cli/cli_impl/ls.py
  skyplane/cli/cli_init.py
  skyplane/cli/cli_internal.py
  skyplane/cli/cli_transfer.py
  skyplane/cli/experiments/provision.py
  skyplane/cli/impl/common.py
  skyplane/cli/impl/cp_replicate_fallback.py
  skyplane/cli/impl/progress_bar.py
  skyplane/cli/usage/client.py
  skyplane/cli/usage/definitions.py
  skyplane/compute/azure/azure_auth.py
  skyplane/config.py
  skyplane/planner/planner.py
  skyplane/planner/solver.py
  skyplane/planner/topology.py
  skyplane/replicate/profiler.py
  skyplane/replicate/replicator_client.py
  skyplane/utils/path.py
  tests/unit_nocloud/test_api_chunker.py
  tests/unit_nocloud/test_cp_replicate.py
Labels: api

#711 Add user configurable option for default location for multi-region buckets
  docs/configure.md
  skyplane/config.py
  skyplane/obj_store/azure_storage_account_interface.py
  skyplane/obj_store/gcs_interface.py
  skyplane/obj_store/s3_interface.py
Labels: enhancement, initial-user

#708 disable OS Login by default for GCP VMs
  skyplane/compute/gcp/gcp_cloud_provider.py
Labels: safe to test
