Repository skyplane-project/skyplane, pull requests merged in 2022-11, with the labels that each got.

#646 [API] Implement monitoring
  skyplane/__init__.py
  skyplane/api/api.py
  skyplane/api/api_demo.py
  skyplane/api/client.py
  skyplane/api/config.py
  skyplane/api/dataplane.py
  skyplane/api/impl/chunker.py
  skyplane/api/impl/provisioner.py
  skyplane/api/impl/tracker.py
  skyplane/api/impl/transfer_job.py
  skyplane/api/test/demo.py
  skyplane/api/tracker.py
  skyplane/api/transfer_config.py
  skyplane/cli/cli_azure.py
  skyplane/compute/aws/aws_network.py
  skyplane/exceptions.py
  skyplane/obj_store/s3_interface.py
  tests/unit_nocloud/test_common.py
Labels: api

#660 Move cloud CLI tools to common file
  skyplane/cli/cli.py
  skyplane/cli/cli_aws.py
  skyplane/cli/cli_azure.py
  skyplane/cli/cli_cloud.py
Labels: CLI

#655 Copy mime types with transfers
  skyplane/api/impl/chunker.py
  skyplane/api/impl/path.py
  skyplane/chunk.py
  skyplane/cli/cli_impl/cp_replicate.py
  skyplane/cli/cli_impl/cp_replicate_fallback.py
  skyplane/gateway/chunk_store.py
  skyplane/gateway/gateway_obj_store.py
  skyplane/gateway/gateway_receiver.py
  skyplane/obj_store/azure_blob_interface.py
  skyplane/obj_store/gcs_interface.py
  skyplane/obj_store/object_store_interface.py
  skyplane/obj_store/s3_interface.py
  skyplane/replicate/replicator_client.py
  tests/integration/cp.py
  tests/interface_util.py
Labels: bug

#665 Move compute requirements under single package
  skyplane/__init__.py
  skyplane/api/auth_config.py
  skyplane/api/client.py
  skyplane/api/dataplane.py
  skyplane/api/impl/chunker.py
  skyplane/api/impl/planner.py
  skyplane/api/impl/provisioner.py
  skyplane/api/impl/tracker.py
  skyplane/api/impl/transfer_job.py
  skyplane/chunk.py
  skyplane/cli/cli.py
  skyplane/cli/cli_cloud.py
  skyplane/cli/cli_impl/cp_replicate.py
  skyplane/cli/cli_impl/cp_replicate_fallback.py
  skyplane/cli/cli_impl/init.py
  skyplane/cli/cli_internal.py
  skyplane/cli/common.py
  skyplane/cli/experiments/cli_profile.py
  skyplane/cli/experiments/provision.py
  skyplane/cli/usage/client.py
  skyplane/compute/__init__.py
  skyplane/compute/aws/aws_cloud_provider.py
  skyplane/compute/aws/aws_server.py
  skyplane/compute/azure/azure_auth.py
  skyplane/compute/azure/azure_cloud_provider.py
  skyplane/compute/cloud_provider.py
  skyplane/compute/gcp/gcp_auth.py
  skyplane/compute/gcp/gcp_cloud_provider.py
  skyplane/compute/server.py
  skyplane/config.py
  skyplane/gateway/chunk_store.py
  skyplane/gateway/gateway_daemon.py
  skyplane/gateway/gateway_daemon_api.py
  skyplane/gateway/gateway_obj_store.py
  skyplane/gateway/gateway_receiver.py
  skyplane/gateway/gateway_sender.py
  skyplane/obj_store/azure_blob_interface.py
  skyplane/obj_store/azure_storage_account_interface.py
  skyplane/obj_store/gcs_interface.py
  skyplane/obj_store/object_store_interface.py
  skyplane/obj_store/s3_interface.py
  skyplane/replicate/replication_plan.py
  skyplane/replicate/replicator_client.py
  skyplane/replicate/solver.py
  skyplane/utils/fn.py
  skyplane/utils/retry.py
Labels: needs-review, quality

#664 Use short UUIDs to limit length of provisioned resources
  skyplane/api/client.py
  skyplane/compute/aws/aws_cloud_provider.py
  skyplane/compute/azure/azure_cloud_provider.py
  skyplane/compute/gcp/gcp_cloud_provider.py
  skyplane/replicate/replicator_client.py
Labels: needs-review, quality

#656 Migrate chunk IDs from ints to UUIDs
  skyplane/api/impl/chunker.py
  skyplane/api/impl/tracker.py
  skyplane/chunk.py
  skyplane/gateway/chunk_store.py
  skyplane/gateway/gateway_daemon_api.py
  skyplane/gateway/gateway_sender.py
  skyplane/replicate/replicator_client.py
Labels: needs-review, api

#669 [API] Performance Logging
  skyplane/api/client.py
  skyplane/api/dataplane.py
  skyplane/api/impl/chunker.py
  skyplane/api/impl/tracker.py
  skyplane/api/impl/transfer_job.py
  skyplane/api/usage/client.py
  skyplane/api/usage/definitions.py
  skyplane/config_paths.py
Labels: api

#671 [API] fix client id issue
  skyplane/api/usage/client.py
Labels: bug

#676 [API] ML training example
  examples/README.md
  examples/pytorch_training.py
  skyplane/compute/server.py
Labels: api

#668 Fix Python 3.7 for config_paths
  poetry.lock
  skyplane/api/dataplane.py
  skyplane/api/impl/chunker.py
  skyplane/api/impl/provisioner.py
  skyplane/compute/gcp/gcp_network.py
  skyplane/config_paths.py
  skyplane/gateway/gateway_obj_store.py
  skyplane/obj_store/s3_interface.py
Labels: needs-review

#689 [broadcast] Fix issues with gateway merge to main
  .pytype.cfg
  skyplane/broadcast/gateway/chunk_store.py
  skyplane/broadcast/gateway/gateway_daemon.py
  skyplane/broadcast/gateway/gateway_daemon_api.py
  skyplane/broadcast/gateway/gateway_program.py
  skyplane/broadcast/gateway/gateway_queue.py
  skyplane/broadcast/gateway/operators/gateway_operator.py
  skyplane/broadcast/gateway/operators/gateway_receiver.py
Labels: bug
